services:
  php-8.2:
    image: php:8.2-apache
    ports:
      - 80:80
    working_dir: /var/www/html
    volumes:
      - './src_php_8.2:/var/www/html'

  php-8.1:
    image: php:8.1-apache
    ports:
      - 81:80
    working_dir: /var/www/html
    volumes:
      - './src_php_8.1:/var/www/html'

  php-7.4:
    image: php:7.4-apache
    ports:
      - 82:80
    working_dir: /var/www/html
    volumes:
      - './src:/var/www/html'

  php-5.6:
    image: php:5.6-apache
    ports:
      - 83:80
    working_dir: /var/www/html
    volumes:
      - './src:/var/www/html'